/*******************************************************************************
 * Copyright (c) 2011 itemis GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Nirmal Sasidharan - initial API and implementation
 ******************************************************************************/

package org.eclipse.rmf.rif11.xsd.validation;

import javax.xml.datatype.XMLGregorianCalendar;

import org.eclipse.rmf.rif11.xsd.ACCESSPOLICIESType;
import org.eclipse.rmf.rif11.xsd.DATATYPESType;
import org.eclipse.rmf.rif11.xsd.SPECGROUPSType;
import org.eclipse.rmf.rif11.xsd.SPECHIERARCHYROOTSType;
import org.eclipse.rmf.rif11.xsd.SPECOBJECTSType;
import org.eclipse.rmf.rif11.xsd.SPECRELATIONSType1;
import org.eclipse.rmf.rif11.xsd.SPECTYPESType;


/**
 * A sample validator interface for {@link org.eclipse.rmf.rif11.xsd.RIF}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RIFValidator {
	boolean validate();

	boolean validateAUTHOR(String value);
	boolean validateCOMMENT(String value);
	boolean validateCOUNTRYCODE(String value);
	boolean validateCREATIONTIME(XMLGregorianCalendar value);
	boolean validateIDENTIFIER(String value);
	boolean validateSOURCETOOLID(String value);
	boolean validateTITLE(String value);
	boolean validateVERSION(String value);
	boolean validateACCESSPOLICIES(ACCESSPOLICIESType value);
	boolean validateDATATYPES(DATATYPESType value);
	boolean validateSPECTYPES(SPECTYPESType value);
	boolean validateSPECOBJECTS(SPECOBJECTSType value);
	boolean validateSPECRELATIONS(SPECRELATIONSType1 value);
	boolean validateSPECGROUPS(SPECGROUPSType value);
	boolean validateSPECHIERARCHYROOTS(SPECHIERARCHYROOTSType value);
}
