/*******************************************************************************
 * Copyright (c) 2011 itemis GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Nirmal Sasidharan - initial API and implementation
 ******************************************************************************/

package org.eclipse.rmf.reqif10.xsd.validation;

import org.eclipse.rmf.reqif10.xsd.DATATYPEDEFINITIONBOOLEAN;
import org.eclipse.rmf.reqif10.xsd.DATATYPEDEFINITIONDATE;
import org.eclipse.rmf.reqif10.xsd.DATATYPEDEFINITIONENUMERATION;
import org.eclipse.rmf.reqif10.xsd.DATATYPEDEFINITIONINTEGER;
import org.eclipse.rmf.reqif10.xsd.DATATYPEDEFINITIONREAL;
import org.eclipse.rmf.reqif10.xsd.DATATYPEDEFINITIONSTRING;
import org.eclipse.rmf.reqif10.xsd.DATATYPEDEFINITIONXHTML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link org.eclipse.rmf.reqif10.xsd.DATATYPESType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DATATYPESTypeValidator {
	boolean validate();

	boolean validateGroup(FeatureMap value);
	boolean validateDATATYPEDEFINITIONBOOLEAN(EList<DATATYPEDEFINITIONBOOLEAN> value);
	boolean validateDATATYPEDEFINITIONDATE(EList<DATATYPEDEFINITIONDATE> value);
	boolean validateDATATYPEDEFINITIONENUMERATION(EList<DATATYPEDEFINITIONENUMERATION> value);
	boolean validateDATATYPEDEFINITIONINTEGER(EList<DATATYPEDEFINITIONINTEGER> value);
	boolean validateDATATYPEDEFINITIONREAL(EList<DATATYPEDEFINITIONREAL> value);
	boolean validateDATATYPEDEFINITIONSTRING(EList<DATATYPEDEFINITIONSTRING> value);
	boolean validateDATATYPEDEFINITIONXHTML(EList<DATATYPEDEFINITIONXHTML> value);
}
