/*******************************************************************************
 * Copyright (c) 2011 itemis GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Nirmal Sasidharan - initial API and implementation
 ******************************************************************************/

package org.eclipse.rmf.reqif10.xsd.validation;

import org.eclipse.rmf.reqif10.xsd.ATTRIBUTEVALUEBOOLEAN;
import org.eclipse.rmf.reqif10.xsd.ATTRIBUTEVALUEDATE;
import org.eclipse.rmf.reqif10.xsd.ATTRIBUTEVALUEENUMERATION;
import org.eclipse.rmf.reqif10.xsd.ATTRIBUTEVALUEINTEGER;
import org.eclipse.rmf.reqif10.xsd.ATTRIBUTEVALUEREAL;
import org.eclipse.rmf.reqif10.xsd.ATTRIBUTEVALUESTRING;
import org.eclipse.rmf.reqif10.xsd.ATTRIBUTEVALUEXHTML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link org.eclipse.rmf.reqif10.xsd.VALUESType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VALUESType1Validator {
	boolean validate();

	boolean validateGroup(FeatureMap value);
	boolean validateATTRIBUTEVALUEBOOLEAN(EList<ATTRIBUTEVALUEBOOLEAN> value);
	boolean validateATTRIBUTEVALUEDATE(EList<ATTRIBUTEVALUEDATE> value);
	boolean validateATTRIBUTEVALUEENUMERATION(EList<ATTRIBUTEVALUEENUMERATION> value);
	boolean validateATTRIBUTEVALUEINTEGER(EList<ATTRIBUTEVALUEINTEGER> value);
	boolean validateATTRIBUTEVALUEREAL(EList<ATTRIBUTEVALUEREAL> value);
	boolean validateATTRIBUTEVALUESTRING(EList<ATTRIBUTEVALUESTRING> value);
	boolean validateATTRIBUTEVALUEXHTML(EList<ATTRIBUTEVALUEXHTML> value);
}
