/*******************************************************************************
 * Copyright (c) 2011 itemis GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Nirmal Sasidharan - initial API and implementation
 ******************************************************************************/

package org.eclipse.rmf.rif12.xsd.validation;

import org.eclipse.rmf.rif12.xsd.ACCESSPOLICIESType;
import org.eclipse.rmf.rif12.xsd.DATATYPESType;
import org.eclipse.rmf.rif12.xsd.SPECGROUPHIERARCHYROOTSType;
import org.eclipse.rmf.rif12.xsd.SPECGROUPSType1;
import org.eclipse.rmf.rif12.xsd.SPECHIERARCHYROOTSType1;
import org.eclipse.rmf.rif12.xsd.SPECOBJECTSType2;
import org.eclipse.rmf.rif12.xsd.SPECRELATIONSType2;
import org.eclipse.rmf.rif12.xsd.SPECTYPESType1;

/**
 * A sample validator interface for {@link org.eclipse.rmf.rif12.xsd.RIFCONTENT}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RIFCONTENTValidator {
	boolean validate();

	boolean validateDATATYPES(DATATYPESType value);
	boolean validateSPECTYPES(SPECTYPESType1 value);
	boolean validateSPECOBJECTS(SPECOBJECTSType2 value);
	boolean validateSPECRELATIONS(SPECRELATIONSType2 value);
	boolean validateSPECGROUPS(SPECGROUPSType1 value);
	boolean validateSPECHIERARCHYROOTS(SPECHIERARCHYROOTSType1 value);
	boolean validateSPECGROUPHIERARCHYROOTS(SPECGROUPHIERARCHYROOTSType value);
	boolean validateACCESSPOLICIES(ACCESSPOLICIESType value);
}
