/*******************************************************************************
 * Copyright (c) 2011 itemis GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Nirmal Sasidharan - initial API and implementation
 ******************************************************************************/

package org.eclipse.rmf.xhtml.validation;

import org.eclipse.rmf.xhtml.AlignType;
import org.eclipse.rmf.xhtml.ValignType;
import org.eclipse.rmf.xhtml.XhtmlTrType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.rmf.xhtml.XhtmlTbodyType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XhtmlTbodyTypeValidator {
	boolean validate();

	boolean validateTr(EList<XhtmlTrType> value);
	boolean validateAlign(AlignType value);
	boolean validateChar(String value);
	boolean validateCharoff(Object value);
	boolean validateClass(String value);
	boolean validateId(String value);
	boolean validateLang(Object value);
	boolean validateSpace(Object value);
	boolean validateStyle(String value);
	boolean validateTitle(String value);
	boolean validateValign(ValignType value);
}
