/*******************************************************************************
 * Copyright (c) 2011 itemis GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Nirmal Sasidharan - initial API and implementation
 ******************************************************************************/

package org.eclipse.rmf.xhtml.validation;

import org.eclipse.rmf.xhtml.FrameType;
import org.eclipse.rmf.xhtml.RulesType;
import org.eclipse.rmf.xhtml.XhtmlCaptionType;
import org.eclipse.rmf.xhtml.XhtmlColType;
import org.eclipse.rmf.xhtml.XhtmlColgroupType;
import org.eclipse.rmf.xhtml.XhtmlTbodyType;
import org.eclipse.rmf.xhtml.XhtmlTfootType;
import org.eclipse.rmf.xhtml.XhtmlTheadType;
import org.eclipse.rmf.xhtml.XhtmlTrType;

import java.math.BigInteger;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.rmf.xhtml.XhtmlTableType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface XhtmlTableTypeValidator {
	boolean validate();

	boolean validateCaption(XhtmlCaptionType value);
	boolean validateCol(EList<XhtmlColType> value);
	boolean validateColgroup(EList<XhtmlColgroupType> value);
	boolean validateThead(XhtmlTheadType value);
	boolean validateTfoot(XhtmlTfootType value);
	boolean validateTbody(EList<XhtmlTbodyType> value);
	boolean validateTr(EList<XhtmlTrType> value);
	boolean validateBorder(BigInteger value);
	boolean validateCellpadding(Object value);
	boolean validateCellspacing(Object value);
	boolean validateClass(String value);
	boolean validateFrame(FrameType value);
	boolean validateId(String value);
	boolean validateLang(Object value);
	boolean validateRules(RulesType value);
	boolean validateSpace(Object value);
	boolean validateStyle(String value);
	boolean validateSummary(String value);
	boolean validateTitle(String value);
	boolean validateWidth(Object value);
}
