/*******************************************************************************
 * Copyright (c) 2011 itemis GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Nirmal Sasidharan - initial API and implementation
 ******************************************************************************/

package org.eclipse.rmf.rif11.xhtml.validation;

import java.util.List;

import org.eclipse.rmf.rif11.xhtml.Shape;


/**
 * A sample validator interface for {@link org.eclipse.rmf.rif11.xhtml.AType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ATypeValidator {
	boolean validate();

	boolean validateCharset(String value);
	boolean validateClass(List<String> value);
	boolean validateCoords(String value);
	boolean validateHref(String value);
	boolean validateHreflang(String value);
	boolean validateId(String value);
	boolean validateName(String value);
	boolean validateRel(List<String> value);
	boolean validateRev(List<String> value);
	boolean validateShape(Shape value);
	boolean validateStyle(String value);
	boolean validateTitle(String value);
	boolean validateType(String value);
}
