/*******************************************************************************
 * Copyright (c) 2011 itemis GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Nirmal Sasidharan - initial API and implementation
 ******************************************************************************/

package org.eclipse.rmf.rif11.xhtml.validation;

import java.util.List;

import org.eclipse.rmf.rif11.xhtml.IsmapType;


/**
 * A sample validator interface for {@link org.eclipse.rmf.rif11.xhtml.ImgType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ImgTypeValidator {
	boolean validate();

	boolean validateAlt(String value);
	boolean validateClass(List<String> value);
	boolean validateHeight(String value);
	boolean validateId(String value);
	boolean validateIsmap(IsmapType value);
	boolean validateLongdesc(String value);
	boolean validateSrc(String value);
	boolean validateStyle(String value);
	boolean validateTitle(String value);
	boolean validateUsemap(String value);
	boolean validateWidth(String value);
}
