<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="ContainmentReferences"
    nsURI="http://www.eclipse.org/rmf/tests/ContainmentReferences"
    nsPrefix="cr">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Root">
    <eAnnotations
        source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details
          key="name"
          value="ROOT"/>
    </eAnnotations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="children"
        upperBound="-1"
        eType="#//Node"
        containment="true">
      <eAnnotations
          source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details
            key="name"
            value="CHILDREN"/>
        <details
            key="kind"
            value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="child"
        eType="#//Node"
        containment="true">
      <eAnnotations
          source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details
            key="name"
            value="CHILD"/>
        <details
            key="kind"
            value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Node">
    <eAnnotations
        source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details
          key="name"
          value="NODE"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
