<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="toolextension" nsURI="http://www.eclipse.org/rmf/serialization/model/toolextension.ecore"
    nsPrefix="toolextension">
  <eClassifiers xsi:type="ecore:EClass" name="Extension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specObjectExtensions" upperBound="-1"
        eType="#//SpecObjectExtension" unsettable="true" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="namespace" value="##targetNamespace"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/sphinx/emf/serialization/XMLPersistenceMappingExtendedMetaData">
        <details key="featureWrapperElement" value="true"/>
        <details key="featureElement" value="false"/>
        <details key="classifierWrapperElement" value="false"/>
        <details key="classifierElement" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecObjectExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extendedDesc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedSpecObject" eType="ecore:EClass ../../../org.eclipse.rmf.reqif10_2/model/reqif10.ecore#//SpecObject"/>
  </eClassifiers>
</ecore:EPackage>
