/*******************************************************************************
 * Copyright (c) 2011 itemis GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Nirmal Sasidharan - initial API and implementation
 ******************************************************************************/

package org.eclipse.rmf.rif12.xhtml.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.util.FeatureMap;
import org.eclipse.rmf.rif12.xhtml.AbbrType;
import org.eclipse.rmf.rif12.xhtml.AcronymType;
import org.eclipse.rmf.rif12.xhtml.BType;
import org.eclipse.rmf.rif12.xhtml.BigType;
import org.eclipse.rmf.rif12.xhtml.BrType;
import org.eclipse.rmf.rif12.xhtml.CiteType;
import org.eclipse.rmf.rif12.xhtml.CodeType;
import org.eclipse.rmf.rif12.xhtml.DelType;
import org.eclipse.rmf.rif12.xhtml.DfnType;
import org.eclipse.rmf.rif12.xhtml.EmType;
import org.eclipse.rmf.rif12.xhtml.IType;
import org.eclipse.rmf.rif12.xhtml.ImgType;
import org.eclipse.rmf.rif12.xhtml.InsType;
import org.eclipse.rmf.rif12.xhtml.KbdType;
import org.eclipse.rmf.rif12.xhtml.ObjectType;
import org.eclipse.rmf.rif12.xhtml.QType;
import org.eclipse.rmf.rif12.xhtml.SampType;
import org.eclipse.rmf.rif12.xhtml.SmallType;
import org.eclipse.rmf.rif12.xhtml.SpanType;
import org.eclipse.rmf.rif12.xhtml.StrikeType;
import org.eclipse.rmf.rif12.xhtml.StrongType;
import org.eclipse.rmf.rif12.xhtml.SubType;
import org.eclipse.rmf.rif12.xhtml.SupType;
import org.eclipse.rmf.rif12.xhtml.TtType;
import org.eclipse.rmf.rif12.xhtml.UType;
import org.eclipse.rmf.rif12.xhtml.VarType;


/**
 * A sample validator interface for {@link org.eclipse.rmf.rif12.xhtml.AContent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AContentValidator {
	boolean validate();

	boolean validateMixed(FeatureMap value);
	boolean validateGroup(FeatureMap value);
	boolean validateBr(EList<BrType> value);
	boolean validateSpan(EList<SpanType> value);
	boolean validateObject(EList<ObjectType> value);
	boolean validateImg(EList<ImgType> value);
	boolean validateTt(EList<TtType> value);
	boolean validateI(EList<IType> value);
	boolean validateB(EList<BType> value);
	boolean validateBig(EList<BigType> value);
	boolean validateSmall(EList<SmallType> value);
	boolean validateU(EList<UType> value);
	boolean validateStrike(EList<StrikeType> value);
	boolean validateEm(EList<EmType> value);
	boolean validateStrong(EList<StrongType> value);
	boolean validateDfn(EList<DfnType> value);
	boolean validateCode(EList<CodeType> value);
	boolean validateQ(EList<QType> value);
	boolean validateSamp(EList<SampType> value);
	boolean validateKbd(EList<KbdType> value);
	boolean validateVar(EList<VarType> value);
	boolean validateCite(EList<CiteType> value);
	boolean validateAbbr(EList<AbbrType> value);
	boolean validateAcronym(EList<AcronymType> value);
	boolean validateSub(EList<SubType> value);
	boolean validateSup(EList<SupType> value);
	boolean validateIns(EList<InsType> value);
	boolean validateDel(EList<DelType> value);
}
