/*******************************************************************************
 * Copyright (c) 2011 itemis GmbH.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Nirmal Sasidharan - initial API and implementation
 ******************************************************************************/

package org.eclipse.rmf.rif12.xhtml.validation;

import java.math.BigInteger;
import java.util.List;

import org.eclipse.emf.common.util.EList;
import org.eclipse.rmf.rif12.xhtml.CaptionType;
import org.eclipse.rmf.rif12.xhtml.ColType;
import org.eclipse.rmf.rif12.xhtml.ColgroupType;
import org.eclipse.rmf.rif12.xhtml.TbodyType;
import org.eclipse.rmf.rif12.xhtml.TfootType;
import org.eclipse.rmf.rif12.xhtml.TheadType;
import org.eclipse.rmf.rif12.xhtml.TrType;


/**
 * A sample validator interface for {@link org.eclipse.rmf.rif12.xhtml.TableType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TableTypeValidator {
	boolean validate();

	boolean validateCaption(CaptionType value);
	boolean validateCol(EList<ColType> value);
	boolean validateColgroup(EList<ColgroupType> value);
	boolean validateThead(TheadType value);
	boolean validateTfoot(TfootType value);
	boolean validateTbody(EList<TbodyType> value);
	boolean validateTr(EList<TrType> value);
	boolean validateBorder(BigInteger value);
	boolean validateCellpadding(String value);
	boolean validateCellspacing(String value);
	boolean validateClass(List<String> value);
	boolean validateId(String value);
	boolean validateStyle(String value);
	boolean validateSummary(String value);
	boolean validateTitle(String value);
	boolean validateWidth(String value);
}
